add_newline = false

format = '''$username@$hostname $directory
$character'''

[character]
success_symbol = '[λ](green)'
error_symbol   = '[ə](red)'

[username]
format = "[$user](red)"
disabled = false
show_always = true

[hostname]
format = "[$hostname$ssh_symbol](white)"
disabled = false
ssh_only = false
